// ARCHIVO GENERADO — no editar a mano.
// Fuente: node scripts/generate-feature-display-names.js (AST de TypeScript sobre
// navigation.service.ts + route.data.titulo de toda la app). Re-generar con ese
// comando cuando se agregue/renombre una pantalla con featureKey nuevo.
//
// Consumido por RoleEdit (security/roles) como fuente principal de nombres legibles
// para los 156+ featureKey del modal "Editar Rol" — humanizeFeatureKey() ahí mismo
// es solo el fallback para featureKey que no aparecen en ningún lado del frontend.

export const FEATURE_DISPLAY_NAMES: Record<string, string> = {
  "accounting.configuration": "Configuración",
  "accounting.dashboard": "Dashboard",
  "accounting.invoices": "Facturas",
  "arquitectura-comercial.actividades": "Arquitectura Comercial - Actividades",
  "arquitectura-comercial.dashboard": "Gestión de Actividades",
  "arquitectura-comercial.entregables": "Arquitectura Comercial - Entregables",
  "arquitectura-comercial.gantt": "Arquitectura Comercial - Gantt",
  "arquitectura-comercial.observaciones.dashboard": "Gestión de Observaciones",
  "arquitectura-comercial.observaciones.lista": "Arquitectura Comercial - Observaciones - Lista",
  "arquitectura-comercial.plantilla": "Arquitectura Comercial - Plantilla",
  "arquitectura-comercial.revisiones.dashboard": "Gestión de Revisiones",
  "arquitectura-comercial.revisiones.lista": "Arquitectura Comercial - Revisiones - Lista",
  "arquitectura-comercial.tareo.enrolamiento": "Arquitectura Comercial - Enrolamiento",
  "arquitectura-comercial.tareo.gestion-permisos": "Arquitectura Comercial - Gestión De Permisos",
  "arquitectura-comercial.tareo.marcar": "Arquitectura Comercial - Tareo",
  "arquitectura-comercial.tareo.reporte": "Arquitectura Comercial - Reporte De Tareo",
  "arquitectura-comercial.tareo.revision": "Arquitectura Comercial - Revisión De Tareo",
  "clinica.agenda": "Clínica",
  "clinica.programaciones": "Clínica - Programaciones",
  "configuracion.aprendizaje": "Centro de aprendizaje",
  "configuracion.area": "Configuración - Áreas",
  "configuracion.companies": "Configuración - Razones Sociales",
  "configuracion.feriados": "Configuración - Feriados Y Días No Laborables",
  "configuracion.proyectos": "Proyectos",
  "configuracion.revisores-areas": "Revisores de Áreas",
  "configuracion.workers": "Configuración - Lista De Trabajadores",
  "contractors.management": "Homologación de contratistas",
  "contractors.registro": "Registro de contratistas",
  "costs.adjudicaciones": "Adjudicaciones",
  "costs.config.adjudicacion-folder": "Carpeta adjudicaciones",
  "costs.config.costos-presupuestos-email": "Correos C. y Ppto.",
  "costs.config.project-link": "Planos por proyecto",
  "costs.config.staff-project-email": "Correos por Proyecto",
  "costs.config.work-item": "Partidas",
  "costs.config.work-item-category": "Partidas de control",
  "costs.config.work-specialty": "Especialidades",
  "costs.dashboard": "Dashboard",
  "evaluaciones.asignaciones": "Asignaciones",
  "evaluaciones.configuracion": "Configuración",
  "evaluaciones.dashboard": "Dashboard",
  "evaluaciones.dashboard-contratistas": "Dashboard contratistas",
  "evaluaciones.dashboard-prevencionistas": "Dashboard Prev./Coord.",
  "evaluaciones.evaluar": "Evaluar residente",
  "evaluaciones.evaluar-contratista": "Evaluar contratista",
  "evaluaciones.evaluar-jefe-ssoma": "Evaluar Jefe SSOMA",
  "evaluaciones.evaluar-supervisor-contratista": "Evaluar supervisor SSOMA",
  "evaluaciones.historial": "Historial",
  "evaluaciones.mi-perfil-prevencionista": "Mi perfil (Prev./Coord.)",
  "evaluaciones.resultados-jefe-ssoma": "Resultados Jefe SSOMA",
  "evaluaciones.ver-contratistas": "Ver eval. contratistas",
  "evaluaciones.ver-supervisores-contratista": "Ver eval. supervisores SSOMA",
  "gestion-administrativa.config.carpeta-adjuntos": "Carpeta Adjuntos",
  "gestion-administrativa.config.correos": "Correos",
  "gestion-administrativa.config.lugares": "Lugares",
  "gestion-administrativa.config.motivos": "Motivos",
  "gestion-administrativa.config.trayectos": "Trayectos",
  "gestion-administrativa.config.visibilidad-salidas": "Visibilidad de Salidas",
  "gestion-administrativa.delegacion-revision": "Delegación de Revisión",
  "gestion-administrativa.gestion-salidas": "Gestión de Salidas",
  "gestion-administrativa.solicitud-salidas": "Solicitud de Salidas",
  "gestion-gth.aprobaciones": "Aprobaciones",
  "gestion-gth.config.categorias-puestos": "Categorías y Puestos",
  "gestion-gth.config.reclutadores": "Reclutadores",
  "gestion-gth.onboarding": "Onboarding",
  "gestion-gth.reclutamiento": "Reclutamiento",
  "gestion-gth.reclutamiento.configuracion": "Reclutamiento - Configuración",
  "gestion-gth.solicitud-personal": "Solicitud de Personal",
  "habilitacion.auditoria": "Habilitación - Auditoría",
  "habilitacion.catalogos.equipos": "Catálogo De Equipos",
  "habilitacion.control-acceso": "Control de Acceso",
  "habilitacion.dossier": "Dossier",
  "habilitacion.empresa": "Habilitación - Empresa",
  "habilitacion.equipos": "Habilitación - Equipos Y Máquinas",
  "habilitacion.evaluacion-supervisores": "Habilitación - Evaluación Supervisores",
  "habilitacion.inducciones": "Habilitación - Inducciones",
  "habilitacion.registros-modelo": "Habilitación - Registros Modelo",
  "habilitacion.reglas": "Habilitación - Reglas De Entregables",
  "habilitacion.sctr-vidaley": "Habilitación - Sctr Y Vida Ley",
  "habilitacion.trabajadores": "Gestión de Ingresos",
  "mejora-continua.config.area-relations": "Relaciones por área",
  "mejora-continua.config.areas": "Áreas",
  "mejora-continua.config.catalog-items": "Ítems de catálogo",
  "mejora-continua.config.catalog-types": "Tipos de catálogo",
  "mejora-continua.config.lecciones-configuracion": "Configuración de lecciones",
  "mejora-continua.config.reminders": "Recordatorios",
  "mejora-continua.config.templates": "Plantillas",
  "mejora-continua.dashboard": "Dashboard",
  "mejora-continua.lessons-learned": "Lecciones aprendidas",
  "mejora-continua.milestone-schedule": "Cronograma de Hitos",
  "planeamiento-bim.configuracion-inicial": "Planeamiento",
  "planeamiento-bim.portafolio": "Planeamiento",
  "projects.actas-reunion": "Actas de Reunión",
  "projects.config.milestones": "Configuraciones",
  "projects.construction-logbook": "Control de cuaderno de obra",
  "projects.cronograma-actividades": "Cronograma de Actividades",
  "projects.cronograma-dashboard": "Dashboard UDP",
  "projects.ivt-control": "Control de IVTs",
  "projects.projects-dashboard": "Dashboard de Proyectos",
  "projects.report-response-control": "Control de respuesta de informes",
  "projects.resident-monitoring-measurement": "Seguimiento y medición de residentes",
  "security.roles": "Roles",
  "security.users": "Usuarios",
  "ssoma.charlas.aprobar": "Revisión Charlas Contratistas",
  "ssoma.gestion.accidentes-incidentes": "Accidentes e Incidentes",
  "ssoma.gestion.amonestaciones": "Amonestaciones y Suspensiones",
  "ssoma.gestion.auditoria-ats": "Auditoría de ATS",
  "ssoma.gestion.charlas": "Charlas & Capacitaciones",
  "ssoma.gestion.checklist": "Checklists SSOMA",
  "ssoma.gestion.horas-hombre": "Horas Hombre",
  "ssoma.gestion.indicadores-proactivos": "Indicadores SSOMA",
  "ssoma.gestion.inspeccion": "Inspecciones",
  "ssoma.gestion.opt": "Obs. Planeada (OPT)",
  "ssoma.gestion.opt.dashboard": "Opt — Dashboard",
  "ssoma.gestion.opt.lista": "Opt — Lista",
  "ssoma.gestion.opt.nuevo": "Nueva Opt",
  "ssoma.gestion.paso": "Prog. Anual SSOMA",
  "ssoma.gestion.presupuesto-materiales": "Presupuesto Materiales",
  "ssoma.gestion.programacion-inducciones": "Programación de Inducciones",
  "ssoma.gestion.proyectos-habilitados": "Proyectos Habilitados SSOMA",
  "ssoma.gestion.rac": "Gestión RAC",
  "ssoma.salud-ocupacional.accidentes": "Accidentes",
  "ssoma.salud-ocupacional.asistente-social": "Asistente Social",
  "ssoma.salud-ocupacional.catalogos": "Salud Ocupacional - Catálogos",
  "ssoma.salud-ocupacional.convalidaciones": "Convalidaciones",
  "ssoma.salud-ocupacional.dashboard": "Dashboard",
  "ssoma.salud-ocupacional.descansos": "Descansos",
  "ssoma.salud-ocupacional.emos": "EMOs",
  "ssoma.salud-ocupacional.emos.configuracion": "EMOs - CONFIGURACIÓN",
  "ssoma.salud-ocupacional.interconsultas": "Interconsultas",
  "ssoma.salud-ocupacional.mi-salud": "Mi Salud",
  "ssoma.salud-ocupacional.mi-salud.configuracion": "Mi Salud - Configuración",
  "ssoma.salud-ocupacional.paso": "PASO",
  "ssoma.salud-ocupacional.programaciones": "Programaciones",
  "ssoma.salud-ocupacional.topico": "Tópico Médico",
  "vecinos.control-licencias": "Control de Licencias",
  "vecinos.croquis": "Croquis",
  "vecinos.dashboard": "Dashboard",
  "vecinos.gestion": "Gestión de Vecinos",
};
